name: terraform
on: push

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_CREATE_PULL_REQUEST }}

      - name: Setup Terraform
        run: >-
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          && echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
          && $HOME/.tfenv/bin/tfenv install

      - name: Setup tfcmt
        run: >-
          curl -sLO https://github.com/suzuki-shunsuke/tfcmt/releases/download/v2.1.0/tfcmt_linux_amd64.tar.gz
          && tar zxvf tfcmt_linux_amd64.tar.gz
          && sudo cp tfcmt /usr/local/bin

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: terraform fmt -check
        run: terraform fmt -check

      - name: terraform init
        run: terraform init

      - name: tfcmt plan
        run: tfcmt plan -- terraform plan

      - name: tfcmt apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: tfcmt apply -- terraform apply -auto-approve
